### ISSUE TITLE
Some questions about the paper

### ISSUE THREAD

**Issue by HaoZhiG** [pcl3dv/PSAvatar#8]
This is an excellent piece of work. However, I have a few questions:

1. In the paper, it is mentioned that "The point-based morphable shape model (PMSM) first converts the FLAME mesh to points. It performs sampling on the surfaces (blue points) and additionally generates samples off the meshes by offsetting the samples on the meshes along their normal directions (black points)." As I understand it, FLAME's set of parameters drives the template points to deform the model. If the mesh is converted to points, how are the points on the mesh and the points sampled along the normal direction driven to deform by these parameters?
2. PMSM models the head based on points. Are these points only converted into 3D Gaussians during the rendering stage? If so, do their attributes and quantities change?

Thank you for your response.

**Comment by pcl3dv** [comment]
Thanks for your attention!
1. The point-based shape model maintains a fixed sampling strategy with the underlying FLAME mesh, which means that the relative relationship between the sampling points and FLAME is determined, so that the shape model is capable of deforming with different 3DMM parameters.
2. After the alignment stage, all the points of shape model will be updated as 3D Gaussian, and the corresponding attributes [color, sigma] are also replaced by [rotation, scale, sh] of Gaussian.

**Comment by HaoZhiG** [comment]
Thank you. I'm grateful for the enlightenment you've provided.
